const allPrizeDatabase = [
  
{
  id: 1,
  name: `FIFTY-FIVE THOUSAND US DOLLAR`,
  price: 55000, 
},
{
  id: 2,
  name: `TEN THOUSAND US DOLLAR`,
  price: 10000, 
}, 
{
  id: 3,
  name: `FIVE THOUSAND US DOLLAR`,
  price: 5000, 
}, 
{
  id: 4,
  name: `FIVE THOUSAND US DOLLAR`,
  price: 2000, 
}, 
{
  id: 5,
  name: `FIVE THOUSAND US DOLLAR`,
  price: 1000, 
}, 
]



const winnerDatabase = [
    {
      id: 1,
      winnerName: 'Hasib Uddin',
      lotteryNumber: '939393939393',
      winnerImage: '/person/person.png',
      winnerAddress: {
        village: 'Shahapur',
        ward: 6,
        union: 'Boalia',
        polisStation: 'Gomostapur',
        district: 'Chapainawabganj',
        division: 'Rajshahi',
        country: 'Bangladesh',
      },
      prize: {
        id: 1,
        name: `IMILAB Imiki SF1E Curved 2.01" AMOLED Calling Smart Watch - Brown`,
        price: 4999,
        link: `https://www.othoba.com/imilab-imiki-sf1e-curved-201-amoled-calling-smart-watch-brown`,
        img: `/lottery/0567967_imilab-imiki-sf1e-curved-201-amoled-calling-smart-watch-brown.jpeg`,
      },
      winningDate: '2024-01-15',
    },
    {
      id: 2,
      winnerName: 'Sadia Akter',
      lotteryNumber: '828282828282',
      winnerImage: '/person/sadia.png',
      winnerAddress: {
        village: 'Kazipara',
        ward: 3,
        union: 'Savar',
        polisStation: 'Savar',
        district: 'Dhaka',
        division: 'Dhaka',
        country: 'Bangladesh',
      },
      prize: {
        id: 5,
        name: `Vision 3.0 Liter Rice Cooker REL-50-05 SS Red (Double Pot)`,
        price: 3670,
        link: `https://www.othoba.com/vision-rice-cooker-30-ltr-100-ss-red-204860`,
        img: `/lottery/0572485_vision-rice-cooker-30-ltr-100-ss-red.jpeg`,
      },
      winningDate: '2024-01-16',
    },
    {
      id: 3,
      winnerName: 'Rahim Mia',
      lotteryNumber: '747474747474',
      winnerImage: '/person/rahim.png',
      winnerAddress: {
        village: 'Chilmari',
        ward: 2,
        union: 'Chilmari',
        polisStation: 'Chilmari',
        district: 'Kurigram',
        division: 'Rangpur',
        country: 'Bangladesh',
      },
      prize: {
        id: 10,
        name: `VISION Electronic Iron 1200W with Overheat and Burn Protection VIS-DEI- 005`,
        price: 1550,
        link: `https://www.othoba.com/vision-electronic-iron-1200w-with-overheat-and-burn-protection-vis-dei-005`,
        img: `/lottery/0539664_vision-electronic-iron-1200w-with-overheat-and-burn-protection-vis-dei-005.jpeg`,
      },
      winningDate: '2024-01-17',
    },
    {
      id: 4,
      winnerName: 'Nadia Rahman',
      lotteryNumber: '555555555555',
      winnerImage: '/person/nadia.png',
      winnerAddress: {
        village: 'Bashundhara',
        ward: 9,
        union: 'Bashundhara',
        polisStation: 'Bashundhara',
        district: 'Dhaka',
        division: 'Dhaka',
        country: 'Bangladesh',
      },
      prize: {
        id: 12,
        name: `Canon EOS 90D 32.5MP DSLR Camera with EF-S 18-135mm IS USM Lens`,
        price: 155000,
        link: `https://www.startech.com.bd/canon-eos-90d-32mp-camera`,
        img: `/lottery/canon-eos-90d-32mp-camera.jpg`,
      },
      winningDate: '2024-01-18',
    },
    {
      id: 5,
      winnerName: 'Abdul Haque',
      lotteryNumber: '222222222222',
      winnerImage: '/person/abdul.png',
      winnerAddress: {
        village: 'Mithapukur',
        ward: 4,
        union: 'Mithapukur',
        polisStation: 'Mithapukur',
        district: 'Rangpur',
        division: 'Rangpur',
        country: 'Bangladesh',
      },
      prize: {
        id: 16,
        name: `AMD Ryzen 5 5600 Custom Gaming Desktop PC`,
        price: 56698,
        link: `https://www.startech.com.bd/amd-ryzen-5-5600-custom-gaming-desktop-pc`,
        img: `/lottery/ryzen-5-5600-500x500.webp`,
      },
      winningDate: '2024-01-19',
    },
    {
      id: 6,
      winnerName: 'Tahmina Akhter',
      lotteryNumber: '989898989898',
      winnerImage: '/person/tahmina.png',
      winnerAddress: {
        village: 'Mirpur',
        ward: 10,
        union: 'Mirpur',
        polisStation: 'Mirpur',
        district: 'Dhaka',
        division: 'Dhaka',
        country: 'Bangladesh',
      },
      prize: {
        id: 18,
        name: `HF.Deluxe - HF Deluxe BS4 13s`,
        price: 113000,
        link: `https://www.heromotocorp.com/en-bd/products/commuter/hf-deluxe.html#specifications`,
        img: `/lottery/hf-delux.png`,
      },
      winningDate: '2024-01-20',
    },
    {
      id: 7,
      winnerName: 'Farhana Islam',
      lotteryNumber: '777777777777',
      winnerImage: '/person/farhana.png',
      winnerAddress: {
        village: 'Badda',
        ward: 12,
        union: 'Badda',
        polisStation: 'Badda',
        district: 'Dhaka',
        division: 'Dhaka',
        country: 'Bangladesh',
      },
      prize: {
        id: 3,
        name: `VISION Glass Door Refrigerator RE-217 Liter Purple Peony Top Mount`,
        price: 37400,
        link: `https://www.othoba.com/vision-glass-door-refrigerator-re-217-liter-purple-peony-top-mount-red00004`,
        img: `/lottery/0570457_vision-glass-door-refrigerator-re-217-liter-purple-peony-top-mount.jpeg`,
      },
      winningDate: '2024-01-21',
    },
    {
      id: 8,
      winnerName: 'Kamal Ahmed',
      lotteryNumber: '111111111111',
      winnerImage: '/person/kamal.png',
      winnerAddress: {
        village: 'Sreemangal',
        ward: 5,
        union: 'Sreemangal',
        polisStation: 'Sreemangal',
        district: 'Moulvibazar',
        division: 'Sylhet',
        country: 'Bangladesh',
      },
      prize: {
        id: 8,
        name: `Proton RG02 Feature Phone Multi Color`,
        price: 1440,
        link: `https://www.othoba.com/proton-rg02-mobile-phone-multi-color`,
        img: `/lottery/0580979_proton-rg02-feature-phone-multi-color.jpeg`,
      },
      winningDate: '2024-01-22',
    },
    {
      id: 9,
      winnerName: 'Fahim Rahman',
      lotteryNumber: '444444444444',
      winnerImage: '/person/fahim.png',
      winnerAddress: {
        village: 'Gulshan',
        ward: 8,
        union: 'Gulshan',
        polisStation: 'Gulshan',
        district: 'Dhaka',
        division: 'Dhaka',
        country: 'Bangladesh',
      },
      prize: {
        id: 6,
        name: `VISION 6Kg Front Loading Washing Machine FLT60`,
        price: 37000,
        link: `https://www.othoba.com/vision-front-loading-washing-machine-flt60-6kg-6kg`,
        img: `/lottery/0572538_vision-front-loading-washing-machine-flt60-6kg-6kg.jpeg`,
      },
      winningDate: '2024-01-23',
    },
    {
      id: 10,
      winnerName: 'Tasnim Jahan',
      lotteryNumber: '666666666666',
      winnerImage: '/person/tasnim.png',
      winnerAddress: {
        village: 'Barishal',
        ward: 7,
        union: 'Barishal',
        polisStation: 'Barishal',
        district: 'Barishal',
        division: 'Barishal',
        country: 'Bangladesh',
      },
      prize: {
        id: 14,
        name: `Edifier H180 Hi-Fi Stereo In-ear Earphone`,
        price: 650,
        link: `https://www.startech.com.bd/edifier-h180-hi-fi-stereo-in-ear-earphone`,
        img: `/lottery/h180-03-500x500.webp`,
      },
      winningDate: '2024-01-24',
    },
    {
      id: 11,
      winnerName: 'Imran Khan',
      lotteryNumber: '121212121212',
      winnerImage: '/person/imran.png',
      winnerAddress: {
        village: 'Satkhira',
        ward: 1,
        union: 'Satkhira',
        polisStation: 'Satkhira',
        district: 'Satkhira',
        division: 'Khulna',
        country: 'Bangladesh',
      },
      prize: {
        id: 7,
        name: `VISION Micro Oven VSN J5 20 Ltr`,
        price: 10500,
        link: `https://www.othoba.com/vision-micro-oven-vsn-j5-20-ltr-204893`,
        img: `/lottery/0572553_vision-micro-oven-vsn-j5-20-ltr.jpeg`,
      },
      winningDate: '2024-01-25',
    },
    {
      id: 12,
      winnerName: 'Nusrat Jahan',
      lotteryNumber: '999999999999',
      winnerImage: '/person/nusrat.png',
      winnerAddress: {
        village: 'Coxs Bazar',
        ward: 2,
        union: 'Coxs Bazar',
        polisStation: 'Coxs Bazar',
        district: 'Coxs Bazar',
        division: 'Chittagong',
        country: 'Bangladesh',
      },
      prize: {
        id: 2,
        name: `Oppo A17 with 4GB 64GB- Blue (Best Price)`,
        price: 16990,
        link: `https://www.othoba.com/oppo-a17-with-4gb-64gb-blue-best-price-opp00026`,
        img: `/lottery/0550740_oppo-a17-with-4gb-64gb-blue-best-price.webp`,
      },
      winningDate: '2024-01-26',
    },
]

export { allPrizeDatabase, winnerDatabase }

